server:
  port: 8080

line.bot:
  channelToken: 3LfxdLWjF3E/EjrQSqthWK6ChV86pURDCQ02vZcuvTxKbxqSZQNWjlNpIFM9vu4haXpZlHKI/MIBW6u1OnWmNh/gbSrPvUFInwrFoob09EppIcQGsZPWJEhqOSfg6DuwHHhOVZQWIFZ07xelceZ7fQdB04t89/1O/w1cDnyilFU=
  channelSecret: b752447c539c7774ddb204dc45aa5b97
  handler.path: /callback

# log config
logging:
  config:
    classpath: logback.xml
  level:
    com:
      example:
        mapper: debug
